AUTH_URL = "https://app.videosdk.live/settings/api-keys?page=1";
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiI1ZjdhZDI1Ny04ZjM3LTQwODctOWQ1MS1hMDBiNmQxZTkxODgiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTczMTAwMTMzMCwiZXhwIjoxNzMxNjA2MTMwfQ.-K2gMUBFqQOHduHCGslGoJinpFhzN367bLGYOthh-0Q";
